### PR TITLE
reorganized contents in all web pages

### PR DESCRIPTION
**Pull request by utkar-sh-ukla**
Changed Designs of several Pages

### CODE REVIEW

**Comment by elizabeth-christensen** [comment]
@utkar-sh-ukla Thank you so much for all your work on this site last year. I have recently joined PgUS to help with a number of projects. One of them was getting your changes added to the website. I have now done that. If you do a hard refresh on https://postgresql.us/ you should see them. Thanks for this work. I realize that its not the most glamours website, but we really like it and appreciate how it looks. I see that you were part of GSOC, so feel free to use this site in any references or portfolios.

I wanted to mention that I added a two-tiered menu to the site, we had quite a few pages under About. I got most of it fixed but the alignment of that menu is slightly off from the other parts of the menu. Here's a link to a GIST with css and base page if you happen to be able to have a fix: https://gist.github.com/elizabeth-christensen/739331344abc6a9578dd3d449512452c.js"></script>

I am not sure why this repo doesn't mirror what's on the site, I'll see if I can get that fixed too.

**Comment by utkar-sh-ukla** [comment]
@elizabeth-christensen, This PR was meant only for Stephen's review. The changes in it mostly focused on reorganizing content that was mentioned in the document shared with me, not completing UI changes. The homepage and header modifications are still unfinished; this submission only represents part of the effort. Stephen wanted to check progress, and I also wanted feedback on the project's current state. Since I didn't hear back from him, I didn't proceed with other changes.

Thanks for sharing the gist. I'll correct the alignment problem with the two-level menu and make the user interface better. Right now, it's missing many things.

If you have any specific adjustments or fixes you'd like to see on the website, please let me know.

**Comment by elizabeth-christensen** [comment]
Hi there! Ok, interesting, I was not aware of this context. I am working on being able to push to this public repo, that would probably help you make additional changes. Stay tuned, hopefully that's a simple fix.

**Comment by utkar-sh-ukla** [comment]
Sounds good! I look forward to it.

**Pull request closed without merging**
